{
  "@t": "2021-04-05T09:12:32.9013490Z",
  "@mt": "Error message:My error\r\nError stack trace:   at WebApiGresol.Controllers.ThirdPartyController.Get() in C:\\Users\\Guru\\source\\repos\\WebApiGresol\\Controllers\\ThirdPartyController.cs:line 36\r\n",
  "@l": "Error",
  "SourceContext": "WebApiGresol.Controllers.ThirdPartyController",
  "ActionId": "8a2c6e3a-9e8f-481f-a476-86867937e876",
  "ActionName": "WebApiGresol.Controllers.ThirdPartyController.Get (WebApiGresol)",
  "RequestId": "80000008-0002-fc00-b63f-84710c7967bb",
  "RequestPath": "/api/ThirdParty",
  "SpanId": "|78e48b0f-47cf47adb1e369cf.",
  "TraceId": "78e48b0f-47cf47adb1e369cf",
  "ParentId": ""
} {
  "@t": "2021-04-05T09:13:09.1022045Z",
  "@mt": "An unhandled exception has occurred while executing the request.",
  "@l": "Error",
  "@x": "System.Exception: My error\r\n   at WebApiGresol.Controllers.ThirdPartyController.Get() in C:\\Users\\Guru\\source\\repos\\WebApiGresol\\Controllers\\ThirdPartyController.cs:line 36\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\r\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\r\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)",
  "EventId": {
    "Id": 1,
    "Name": "UnhandledException"
  },
  "SourceContext": "Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware",
  "RequestId": "80000008-0002-fc00-b63f-84710c7967bb",
  "RequestPath": "/api/ThirdParty",
  "SpanId": "|78e48b0f-47cf47adb1e369cf.",
  "TraceId": "78e48b0f-47cf47adb1e369cf",
  "ParentId": ""
}
